### ISSUE TITLE
Database error after 4.0.5 update

### ISSUE THREAD

**Issue by tucuman** [petervanderdoes/AVH-Extended-Categories#8]
Hi Peter!
After 4.0.5 hit production we noticed the following Error:

Notice: Ungültige Taxonomie in .../wp-content/plugins/extended-categories-widget/4.2/class/avh-ec.category-group.php on line 240

Notice: Ungültige Taxonomie in .../wp-content/plugins/extended-categories-widget/4.2/class/avh-ec.category-group.php on line 250

Interestingly enough I could find no 4.0.5 version tag. After diving into the code I can see function avh_wp_list_categories got 'activated' in /avh-ec.core.php and error triggering set into place in avh-ec.category-group.php. Can U help?

Thank You, Jan

**Comment by petervanderdoes** [comment]
So it seems the taxonomy is not registered, which is confusing me. I don't get this error, but you are not alone.
In order to dig deeper into this I would like to ask you if I could send you a file with an extra check to see if the taxonomy gets registered.

If you are willing to help out with this one it would be very helpful, if not I understand as well.

**Comment by tucuman** [comment]
Hi Peter - yes, go ahead, send me that file, I'll run the test - no problem!

Thank you for responding so quickly

Viele Grüße - Best regards - Cordiales saludos

Jan Torres W.
mobil: +49 157 5361 5465

**Comment by petervanderdoes** [comment]
If you can do it with Github that would be nice:
I create a new branch bugfix/invalid_taxonomy
The file that I changed is 4.2/class/avh-ec.category-group.php

I've added an extra trigger to see if the taxonomy is registered.

See this link for what I added: https://github.com/petervanderdoes/AVH-Extended-Categories/blob/bugfix/invalid_taxonomy/4.2/class/avh-ec.category-group.php#L197

**Comment by tucuman** [comment]
Peter, I'll return to this test in the afternoon. It's 6 am now in
Germany and I need to get ready for work.

Viele Grüße - Best regards - Cordiales saludos

Jan Torres W.
mobil: +49 157 5361 5465

**Comment by tucuman** [comment]
I replaced avh-ec.category-group.php. But what do I need to call now? I cannot see any difference on the frontend or wp-backend whatsoever.

**Comment by petervanderdoes** [comment]
Do you still get the same error you originally posted?

**Comment by tucuman** [comment]
yes I still get the same error.

**Comment by petervanderdoes** [comment]
I made another change, this time in `4.2/class/avh-ec.core.php`

I initialize the category group class earlier.
See this: https://github.com/petervanderdoes/AVH-Extended-Categories/blob/bugfix/invalid_taxonomy/4.2/class/avh-ec.core.php#L219

**Comment by tucuman** [comment]
Great! Errors gone! Thank you!
